### ISSUE TITLE
excerpt - post display size

### ISSUE THREAD

**Issue by yatesj9** [dongri/Coder#5]
Is there a way to limit the character count for the excerpt??

**Comment by ascendedguard** [comment]
You should be able to edit the `{{content}}` blocks in [index.hbs](https://github.com/dongri/Coder/blob/master/index.hbs#L19) to specify the number of words:

```
{{content words="100"}}
```

I'm not sure if any other pages would need to be modified, since I didn't test. Documentation here: http://docs.ghost.org/fr/themes/#content-
